services:

  mysql:
    build:
      dockerfile: ./mysql/Dockerfile
      context: .
      target: dev_mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./volumes/databases:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
